version: '3.8'

services:
  ragkku-web:
    image: nginx:alpine
    container_name: ragkku-web
    ports:
      - "3000:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ragkku.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.ragkku.entrypoints=websecure"
      - "traefik.http.routers.ragkku.tls.certresolver=letsencrypt"

  ragkku-proxy:
    image: nginx:alpine
    container_name: ragkku-proxy
    ports:
      - "3001:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    environment:
      - N8N_ENDPOINT=https://n8n.yanwarpro.my.id
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ragkku-proxy.rule=Host(`api.your-domain.com`)"
      - "traefik.http.routers.ragkku-proxy.entrypoints=websecure"
      - "traefik.http.routers.ragkku-proxy.tls.certresolver=letsencrypt"

networks:
  default:
    name: ragkku-network
